---
title: "Final project - Airbnb Pricing in Amsterdam"
author: Lukas Cerno, Hederik de Vries & Casper Roex
date: "16 June 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo=TRUE, eval=FALSE, tidy=TRUE}
getwd()
setwd("../Final-project")
list.files()
rm(list=ls()) # Clean up the memory, if we want to rerun from scratch
```

## Business objective



## Including Plots

```{r echo=TRUE, eval=TRUE, tidy=TRUE}
ProjectData <- read.csv("Data/Airbnb_main.csv", sep=";", dec=",") # this contains only the matrix ProjectData
  ProjectData=data.matrix(ProjectData) 
colnames(ProjectData)<-gsub("\\."," ",colnames(ProjectData))
```

```{r echo=FALSE, message=FALSE, prompt=FALSE, results='asis'}
show_data = data.frame(round(ProjectData,2))[1:50,]
show_data$Variables = rownames(show_data)
m1<-gvisTable(show_data,options=list(showRowNumber=TRUE,width=1220, height=min(400,27*(nrow(show_data)+1)),allowHTML=TRUE,page='disable'))
print(m1,'chart')
```